txt_welcome_note = "//div[contains(text(), 'Welcome to Zinier')]"
txt_box_env = "//input[@placeholder='Enter Environment']"
txt_box_org = "//input[@placeholder='Enter organization name']"
txt_box_username = "//input[@type='email']"
txt_box_password = "//input[@type='password']"
btn_element = "//button[@type='button']"